-- Add migration script here
CREATE TABLE IF NOT EXISTS beta_applicants (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_key TEXT NOT NULL UNIQUE,
    email TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_beta_applicants_public_key
    ON beta_applicants (public_key);