-- Add migration script here
CREATE TABLE IF NOT EXISTS badges (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    score INTEGER NOT NULL DEFAULT 1
);

CREATE INDEX IF NOT EXISTS idx_badges_title
    ON badges (title);

INSERT INTO badges (title, description) VALUES
    ('First Cube Cat', 'Register for our private beta'),
    ('Silver Early Supporter', 'Hold 10.000 $CATICS or more'),
    ('Golden Early Supporter', 'Hold 100.000 $CATICS or more'),
    ('Distinguished Early Supporter', 'Hold 1.000.000 $CATICS or more'),
    ('Early Miner', 'Mine with your cat in season 0'),
    ('Stronger Cat', 'Upgrade a cat to level 2'),
    ('Planetary Feline', 'Stake at least 100 $JUP');


CREATE TABLE IF NOT EXISTS beta_applicant_badges (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    beta_applicant_id INTEGER NOT NULL REFERENCES beta_applicants(id) ON DELETE CASCADE,
    badge_id INTEGER NOT NULL REFERENCES badges(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_beta_applicant_badges_beta_applicant_id
    ON beta_applicant_badges (beta_applicant_id);

CREATE INDEX IF NOT EXISTS idx_beta_applicant_badges_badge_id
    ON beta_applicant_badges (badge_id);

INSERT INTO beta_applicant_badges (beta_applicant_id, badge_id, created_at)
SELECT id, 1, created_at
FROM beta_applicants;