-- Add migration script here
-- Create the new leaderboard table for cumulative daily rewards system
CREATE TABLE IF NOT EXISTS leaderboard_entries (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    beta_applicant_id INTEGER NOT NULL REFERENCES beta_applicants(id) ON DELETE CASCADE,
    public_key TEXT NOT NULL,
    total_score INTEGER NOT NULL DEFAULT 0, 
    rank INTEGER NOT NULL,
    previous_rank INTEGER NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    UNIQUE (beta_applicant_id),
    UNIQUE (rank)
);

-- Performance indexes for fast leaderboard queries
CREATE INDEX IF NOT EXISTS idx_leaderboard_entries_rank
    ON leaderboard_entries (rank);
CREATE INDEX IF NOT EXISTS idx_leaderboard_entries_public_key
    ON leaderboard_entries (public_key);
CREATE INDEX IF NOT EXISTS idx_leaderboard_entries_beta_applicant_id
    ON leaderboard_entries (beta_applicant_id);
CREATE INDEX IF NOT EXISTS idx_leaderboard_entries_score_created_at
    ON leaderboard_entries (total_score DESC, created_at ASC);

-- Populate table with current state from the beta_applicants_leaderboard view
INSERT INTO leaderboard_entries (beta_applicant_id, public_key, total_score, rank, previous_rank, created_at, updated_at)
WITH ranked_applicants AS (
    SELECT
        id as beta_applicant_id,
        public_key,
        total_score,
        created_at,
        ROW_NUMBER() OVER (ORDER BY total_score DESC, created_at ASC) as rank,
        NULL::INTEGER as previous_rank,
        NOW() as updated_at
    FROM beta_applicants_leaderboard
)
SELECT beta_applicant_id, public_key, total_score, rank, previous_rank, created_at, updated_at
FROM ranked_applicants;
