-- Add cats and cat levels tables for idle progressive game

-- Cats table - main cat definitions
CREATE TABLE IF NOT EXISTS cats (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    sprite_idle TEXT NOT NULL,
    sprite_mining TEXT NOT NULL,
    is_starter BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Cat levels table - progression stats for each cat
CREATE TABLE IF NOT EXISTS cat_levels (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cat_id INTEGER NOT NULL REFERENCES cats(id) ON DELETE CASCADE,
    level INTEGER NOT NULL,
    damage BIGINT NOT NULL,           -- Stored as hundredths (1.25 = 125)
    critical_chance BIGINT NOT NULL,      -- Stored as hundredths (0.15 = 15)
    critical_multiplier BIGINT NOT NULL,  -- Stored as hundredths (2.50 = 250)
    cost BIGINT NOT NULL,             -- Stored as hundredths
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    UNIQUE (cat_id, level)
);

-- Performance indexes
CREATE INDEX IF NOT EXISTS idx_cats_is_starter 
    ON cats (is_starter);

CREATE INDEX IF NOT EXISTS idx_cat_levels_cat_id 
    ON cat_levels (cat_id);

CREATE INDEX IF NOT EXISTS idx_cat_levels_level 
    ON cat_levels (level);

CREATE INDEX IF NOT EXISTS idx_cat_levels_cat_id_level 
    ON cat_levels (cat_id, level);

-- Insert initial cats data for idle progressive game
INSERT INTO cats (name, description, sprite_idle, sprite_mining, is_starter) VALUES
    ('Voidwhisker', 'A fiery street cat that leaves scorched marks wherever it strikes.', 'https://fiji-solutions.s3.eu-central-1.amazonaws.com/catalytics_game/sprites/cats/idle/cat_1.png', 'https://fiji-solutions.s3.eu-central-1.amazonaws.com/catalytics_game/sprites/cats/mining/cat_1.png', true),
    ('Emberpaw', 'A silent cat from the shadows. Its attacks feel colder than darkness.', 'https://fiji-solutions.s3.eu-central-1.amazonaws.com/catalytics_game/sprites/cats/idle/cat_2.png', 'https://fiji-solutions.s3.eu-central-1.amazonaws.com/catalytics_game/sprites/cats/mining/cat_2.png', true),
    ('Mechakitty', 'Half cat, half machine. Built for precision and relentless mining.', 'https://fiji-solutions.s3.eu-central-1.amazonaws.com/catalytics_game/sprites/cats/idle/cat_3.png', 'https://fiji-solutions.s3.eu-central-1.amazonaws.com/catalytics_game/sprites/cats/mining/cat_3.png', true),
    ('Voidwhisker', 'A fiery street cat that leaves scorched marks wherever it strikes.', 'https://fiji-solutions.s3.eu-central-1.amazonaws.com/catalytics_game/sprites/cats/idle/cat_4.png', 'https://fiji-solutions.s3.eu-central-1.amazonaws.com/catalytics_game/sprites/cats/mining/cat_4.png', false),
    ('Emberpaw', 'A silent cat from the shadows. Its attacks feel colder than darkness.', 'https://fiji-solutions.s3.eu-central-1.amazonaws.com/catalytics_game/sprites/cats/idle/cat_5.png', 'https://fiji-solutions.s3.eu-central-1.amazonaws.com/catalytics_game/sprites/cats/mining/cat_5.png', false),
    ('Mechakitty', 'Half cat, half machine. Built for precision and relentless mining.', 'https://fiji-solutions.s3.eu-central-1.amazonaws.com/catalytics_game/sprites/cats/idle/cat_6.png', 'https://fiji-solutions.s3.eu-central-1.amazonaws.com/catalytics_game/sprites/cats/mining/cat_6.png', false),
    ('Voidwhisker', 'A fiery street cat that leaves scorched marks wherever it strikes.', 'https://fiji-solutions.s3.eu-central-1.amazonaws.com/catalytics_game/sprites/cats/idle/cat_7.png', 'https://fiji-solutions.s3.eu-central-1.amazonaws.com/catalytics_game/sprites/cats/mining/cat_7.png', false),
    ('Emberpaw', 'A silent cat from the shadows. Its attacks feel colder than darkness.', 'https://fiji-solutions.s3.eu-central-1.amazonaws.com/catalytics_game/sprites/cats/idle/cat_8.png', 'https://fiji-solutions.s3.eu-central-1.amazonaws.com/catalytics_game/sprites/cats/mining/cat_8.png', false),
    ('Mechakitty', 'Half cat, half machine. Built for precision and relentless mining.', 'https://fiji-solutions.s3.eu-central-1.amazonaws.com/catalytics_game/sprites/cats/idle/cat_9.png', 'https://fiji-solutions.s3.eu-central-1.amazonaws.com/catalytics_game/sprites/cats/mining/cat_9.png', false),
    ('Emberpaw', 'A silent cat from the shadows. Its attacks feel colder than darkness.', 'https://fiji-solutions.s3.eu-central-1.amazonaws.com/catalytics_game/sprites/cats/idle/cat_10.png', 'https://fiji-solutions.s3.eu-central-1.amazonaws.com/catalytics_game/sprites/cats/mining/cat_10.png', false),
    ('Mechakitty', 'Half cat, half machine. Built for precision and relentless mining.', 'https://fiji-solutions.s3.eu-central-1.amazonaws.com/catalytics_game/sprites/cats/idle/cat_11.png', 'https://fiji-solutions.s3.eu-central-1.amazonaws.com/catalytics_game/sprites/cats/mining/cat_11.png', false);

-- Insert cat levels data (levels 1-10 for each cat, with critical_chance capped at 100%)
INSERT INTO cat_levels (cat_id, level, damage, critical_chance, critical_multiplier, cost) VALUES
    -- Cat 1: Voidwhisker (base: 3.00, 0.30, 9.67, 12.50)
    (1, 1, 300, 30, 967, 1250),
    (1, 2, 600, 60, 1934, 2500),
    (1, 3, 1200, 100, 3868, 5000),
    (1, 4, 2400, 100, 7736, 10000),
    (1, 5, 4800, 100, 15472, 20000),
    (1, 6, 9600, 100, 30944, 40000),
    (1, 7, 19200, 100, 61888, 80000),
    (1, 8, 38400, 100, 123776, 160000),
    (1, 9, 76800, 100, 247552, 320000),
    (1, 10, 153600, 100, 495104, 640000),
    
    -- Cat 2: Emberpaw (base: 5.00, 0.20, 14.00, 12.50)
    (2, 1, 500, 20, 1400, 1250),
    (2, 2, 1000, 40, 2800, 2500),
    (2, 3, 2000, 80, 5600, 5000),
    (2, 4, 4000, 100, 11200, 10000),
    (2, 5, 8000, 100, 22400, 20000),
    (2, 6, 16000, 100, 44800, 40000),
    (2, 7, 32000, 100, 89600, 80000),
    (2, 8, 64000, 100, 179200, 160000),
    (2, 9, 128000, 100, 358400, 320000),
    (2, 10, 256000, 100, 716800, 640000),
    
    -- Cat 3: Mechakitty (base: 4.00, 0.10, 27.00, 12.50)
    (3, 1, 400, 10, 2700, 1250),
    (3, 2, 800, 20, 5400, 2500),
    (3, 3, 1600, 40, 10800, 5000),
    (3, 4, 3200, 80, 21600, 10000),
    (3, 5, 6400, 100, 43200, 20000),
    (3, 6, 12800, 100, 86400, 40000),
    (3, 7, 25600, 100, 172800, 80000),
    (3, 8, 51200, 100, 345600, 160000),
    (3, 9, 102400, 100, 691200, 320000),
    (3, 10, 204800, 100, 1382400, 640000),
    
    -- Cat 4: Voidwhisker variant (base: 3.00, 0.50, 6.20, 12.50)
    (4, 1, 300, 50, 620, 1250),
    (4, 2, 600, 100, 1240, 2500),
    (4, 3, 1200, 100, 2480, 5000),
    (4, 4, 2400, 100, 4960, 10000),
    (4, 5, 4800, 100, 9920, 20000),
    (4, 6, 9600, 100, 19840, 40000),
    (4, 7, 19200, 100, 39680, 80000),
    (4, 8, 38400, 100, 79360, 160000),
    (4, 9, 76800, 100, 158720, 320000),
    (4, 10, 153600, 100, 317440, 640000),
    
    -- Cat 5: Emberpaw variant (base: 5.00, 0.05, 53.00, 12.50)
    (5, 1, 500, 5, 5300, 1250),
    (5, 2, 1000, 10, 10600, 2500),
    (5, 3, 2000, 20, 21200, 5000),
    (5, 4, 4000, 40, 42400, 10000),
    (5, 5, 8000, 80, 84800, 20000),
    (5, 6, 16000, 100, 169600, 40000),
    (5, 7, 32000, 100, 339200, 80000),
    (5, 8, 64000, 100, 678400, 160000),
    (5, 9, 128000, 100, 1356800, 320000),
    (5, 10, 256000, 100, 2713600, 640000),
    
    -- Cat 6: Mechakitty variant (base: 4.00, 0.05, 17.00, 12.50)
    (6, 1, 400, 5, 1700, 1250),
    (6, 2, 800, 10, 3400, 2500),
    (6, 3, 1600, 20, 6800, 5000),
    (6, 4, 3200, 40, 13600, 10000),
    (6, 5, 6400, 80, 27200, 20000),
    (6, 6, 12800, 100, 54400, 40000),
    (6, 7, 25600, 100, 108800, 80000),
    (6, 8, 51200, 100, 217600, 160000),
    (6, 9, 102400, 100, 435200, 320000),
    (6, 10, 204800, 100, 870400, 640000),
    
    -- Cat 7: Voidwhisker variant (base: 3.00, 0.20, 5.00, 12.50)
    (7, 1, 300, 20, 500, 1250),
    (7, 2, 600, 40, 1000, 2500),
    (7, 3, 1200, 80, 2000, 5000),
    (7, 4, 2400, 100, 4000, 10000),
    (7, 5, 4800, 100, 8000, 20000),
    (7, 6, 9600, 100, 16000, 40000),
    (7, 7, 19200, 100, 32000, 80000),
    (7, 8, 38400, 100, 64000, 160000),
    (7, 9, 76800, 100, 128000, 320000),
    (7, 10, 153600, 100, 256000, 640000),
    
    -- Cat 8: Emberpaw variant (base: 5.00, 0.10, 9.00, 12.50)
    (8, 1, 500, 10, 900, 1250),
    (8, 2, 1000, 20, 1800, 2500),
    (8, 3, 2000, 40, 3600, 5000),
    (8, 4, 4000, 80, 7200, 10000),
    (8, 5, 8000, 100, 14400, 20000),
    (8, 6, 16000, 100, 28800, 40000),
    (8, 7, 32000, 100, 57600, 80000),
    (8, 8, 64000, 100, 115200, 160000),
    (8, 9, 128000, 100, 230400, 320000),
    (8, 10, 256000, 100, 460800, 640000),
    
    -- Cat 9: Mechakitty variant (base: 4.00, 0.01, 21.00, 12.50)
    (9, 1, 400, 1, 2100, 1250),
    (9, 2, 800, 2, 4200, 2500),
    (9, 3, 1600, 4, 8400, 5000),
    (9, 4, 3200, 8, 16800, 10000),
    (9, 5, 6400, 16, 33600, 20000),
    (9, 6, 12800, 32, 67200, 40000),
    (9, 7, 25600, 64, 134400, 80000),
    (9, 8, 51200, 100, 268800, 160000),
    (9, 9, 102400, 100, 537600, 320000),
    (9, 10, 204800, 100, 1075200, 640000),
    
    -- Cat 10: Emberpaw variant (base: 5.00, 0.02, 11.00, 12.50)
    (10, 1, 500, 2, 1100, 1250),
    (10, 2, 1000, 4, 2200, 2500),
    (10, 3, 2000, 8, 4400, 5000),
    (10, 4, 4000, 16, 8800, 10000),
    (10, 5, 8000, 32, 17600, 20000),
    (10, 6, 16000, 64, 35200, 40000),
    (10, 7, 32000, 100, 70400, 80000),
    (10, 8, 64000, 100, 140800, 160000),
    (10, 9, 128000, 100, 281600, 320000),
    (10, 10, 256000, 100, 563200, 640000),
    
    -- Cat 11: Mechakitty variant (base: 4.00, 0.03, 7.67, 12.50)
    (11, 1, 400, 3, 767, 1250),
    (11, 2, 800, 6, 1534, 2500),
    (11, 3, 1600, 12, 3068, 5000),
    (11, 4, 3200, 24, 6136, 10000),
    (11, 5, 6400, 48, 12272, 20000),
    (11, 6, 12800, 96, 24544, 40000),
    (11, 7, 25600, 100, 49088, 80000),
    (11, 8, 51200, 100, 98176, 160000),
    (11, 9, 102400, 100, 196352, 320000),
    (11, 10, 204800, 100, 392704, 640000);
